name: Backend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '21'

      - name: Verify Java version
        run: java -version

      - name: Build with Maven
        run: mvn clean install
        working-directory: backend

      - name: Run tests
        run: mvn test
        working-directory: backend

      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      

      - name: Docker Build and Push
        run: |
          docker build -t ghcr.io/${{ env.REPO_NAME }}/backend:latest .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ github.repository }}/backend:latest
